server:
  port: 7777
spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider     # 应用名称
  scan:     # 接口实现者（服务实现）包
    base-packages: com.cyzc.dubbo.service.impl
  registry:   # 注册中心信息
    address: zookeeper://xxx.xxx.xx.xxx:2181
    timeout: 1000
  protocol:
    name: dubbo     # 协议名称
    port: 20880    # 协议端口